### ISSUE TITLE
Bug: 0.0.6 seems to be broken with SSR

### ISSUE THREAD

**Issue by WarningImHack3r** [huntabyte/mode-watcher#28]
I just upgraded `mode-watcher` to 0.0.6, restarted the dev server I was working on and suddenly my website isn't adapting to the OS theme (dark) anymore, it stays white after refreshing, no matter which theme I choose.

After a quick look into the console, I noticed this:
<img src="https://github.com/huntabyte/mode-watcher/assets/43064022/7417419a-d5c1-4139-a378-d58f12ce2b8d" alt="0.0.6 bug" width="500" />

I dug the changes, and I suppose it comes from importing `withoutTransition`, for some reason.

I know you're really busy with all the fantastic projects you maintain but can you take a look, please?

**Comment by ollema** [comment]
This was a concern when I worked with this function also, hence why I added this comment:

https://github.com/huntabyte/mode-watcher/blob/2fcc614d470a345031db6b2ccf06490f42b5fc34/src/lib/mode.ts#L71

maybe there is a workaround?

**Comment by ollema** [comment]
for now, I think the easiest fix is just to not use this `withouTransition` in `setInitialClassState`. I don’t think it’s needed there anyways

**Comment by huntabyte** [comment]
This _should_ be fixed with the latest release. Let me know if not and I'll check it out when I get home!

**Comment by WarningImHack3r** [comment]
It does! Thanks @ollema, @HubbeDev & @huntabyte, you rock!
