### ISSUE TITLE
`dark` html class not added by default when system is dark

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/mode-watcher#37]
## Demo 

Video demo. The OS is set to dark mode, and video starts with a hard refresh (the flash). It's expected to be in dark mode by default,  but isn't

https://github.com/huntabyte/mode-watcher/assets/50032291/e4dd4149-1dcc-4b58-94e4-ec29b2d260ad

## Repro

1. Load website with OS system set to dark mode. (Expect `dark` to exist as a class on the root `html` element, but it is not present.) ❌
2. Clicking `setMode('light')`, make changes as expected to the class and color scheme. ✅
3. Clicking `setMode('dark')`, makes changes as expected to the class and color scheme. ✅

Using this code:

```svelte
// +layout.svelte
<script lang="ts">
  import { ModeWatcher } from 'mode-watcher';
</script>

<ModeWatcher />
<slot />
```

```svelte
<script>
  import { setMode } from 'mode-watcher';
</script>

<button on:click={() => setMode('light')}>Set Light Mode</button>
<button on:click={() => setMode('dark')}>Set Dark Mode</button>
```

Possibly related to: https://github.com/huntabyte/mode-watcher/issues/22 ? 

## Versions

```json
"mode-watcher": "^0.1.1",
"@sveltejs/kit": "^1.27.1",
"svelte": "^4.2.2",
```

**Comment by huntabyte** [comment]
I'm not able to reproduce this on my end.

**Comment by huntabyte** [comment]
https://stackblitz.com/github/huntabyte/mode-watcher

**Comment by jasongitmail** [comment]
yep, I cleared localStorage. Loading the site sets localStorage's `mode` as `system` initially, but not the root element's `dark` class. 

<img width="526" src="https://github.com/huntabyte/mode-watcher/assets/50032291/7251d895-ef25-4fa5-948e-e5ef5f7b32c6">
<img width="429" src="https://github.com/huntabyte/mode-watcher/assets/50032291/fc11f13a-f210-4504-aee1-f663196bed47">

Tested in Chrome and Safari.

Thanks for the stackblitz. I'll let you know what I find with my my app.

**Comment by jasongitmail** [comment]
It was a conflict with the import of my old remnant dark mode toggle, even though I commented out the component itself, while evaluating `mode-watcher`. Sorry about that. 

The Stackblitz is quite helpful though! Might be worth linking to that from the README.
