### ISSUE TITLE
FOUC

### ISSUE THREAD

**Issue by jasongitmail** [huntabyte/mode-watcher#39]
I notice that @ollema's PR [includes some handling to mitigate FOUC](https://github.com/huntabyte/mode-watcher/pull/31/files#diff-26370913315c68396addacd23c4e2075df8e975024c3eeb6807e5e68b8838354L73).

However, I still see FOUC briefly on initial load, when system is set to dark mode. 

<img width="487" src="https://github.com/huntabyte/mode-watcher/assets/50032291/e63e49e2-212a-4217-bc0f-27079f7662b5">

(This is from Safari, but this can be observed in Chrome by enabling "slow 3G" in the network inspector and reloading, after clearing local storage of course.) 

My hypothesis is that this because the code lives within a `.svelte` component, rather than `app.html`. 

It's not a big deal, and I can imagine the current design was chosen to reduce work for a dev implementing it, which seems reasonable. But I wanted to ask @ollema if he noticed this remaining FOUC and if there is a way to mitigate it fully.

**Comment by ollema** [comment]
hi @jasongitmail.

as you noticed, my patch _also_ included mitigations to avoid FOUC.

this already existed in `mode-watcher` and the `<LightSwitch>` component from skeleton that the original code drew a lot of inspiration from. my patch did not change how this is implemented.

both before my patch and now, a snippet that sets the correct class on the `html` element is added to the `<head>` element. this means that it should be loaded and executed fairly quickly.

in fact, I am not able to replicate this FOUC with dark mode. are you experimenting with a deployed app or with a dev server? maybe that is a factor.

here I'm trying the same safari timeline tool when I have deleted `localStorage` variables and then do a full refresh

<img width="1179" alt="Screenshot 2023-11-24 at 11 31 30" src="https://github.com/huntabyte/mode-watcher/assets/31876997/b3b7e877-95eb-4c5f-af8e-02e287eb305e">

I wonder why this is not working for you?

**Comment by jasongitmail** [comment]
@ollema Found the cause. It's CSP related.

```js
    // svelte.config.js
    ...
    csp: {
      directives: {
        'base-uri': ['none'],
        'connect-src': ['self', 'cloudflareinsights.com'],
        // 'default-src': ['self'],
        'img-src': ['*'],
        'object-src': ['none'],
        // 'script-src': ['self', 'static.cloudflareinsights.com'],
        'style-src': ['self', 'unsafe-inline'],
      },
    },
   ...
```

If I enable either `default-src` or `script-src` rules, either individually or both together, the FOUC occurs. If these properties exist even with an empty array value or a `'*'` value, then FOUC still occurs. Commenting those two properties out removes the FOUC. 

Seems like its a conflict with the sha256 inline script CSP added for mode-watcher's inline script, where svelte.config.js' CSP clobbers it somehow.

**Comment by ollema** [comment]
interesting! so is this still an issue with mode-watcher? if so, do you know how to fix it?

or should this issue be closed?

**Comment by jasongitmail** [comment]
Seems to be an issue with mode-watcher. I don't know the solution yet. Would be curious if you guys have ideas

**Comment by ollema** [comment]
see: https://github.com/sveltejs/kit/discussions/4952 for additional context

**Comment by jasongitmail** [comment]
oh interesting. 

I might just live with the FOUC for now, rather than disable my CSP rules, and hope the core devs address that eventually.

We can close this then.
