### ISSUE TITLE
Compare with svelte-themes

### ISSUE THREAD

**Issue by xmlking** [huntabyte/mode-watcher#44]
Just came across this lib and svelte-themes
Wonder if there is nay feature parity w.r.t  svelte-themes

https://github.com/beynar/svelte-themes

**Comment by ollema** [comment]
I think these two projects are pretty similar - however this project is under active development while `svelte-themes` has not seen any activity for quite a while (maybe it's not needed though!)

does this answer your question @xmlking?

**Comment by xmlking** [comment]
Thanks @ollema i will stick with [mode-watcher](https://github.com/huntabyte/mode-watcher)

**Comment by ollema** [comment]
if so, feel free to close this issue :)
________________________________
