### ISSUE TITLE
theme stored in localStorage is not used as mode value on Mount

### ISSUE THREAD

**Issue by jonasfroeller** [huntabyte/mode-watcher#45]
I am confused. Why do I have to set the mode manually onMount, if it is correctly stored in the mode store?

```ts
<script lang="ts">
	import LocaleSwitcher from '$lib/components/LocaleSwitcher.svelte';
	import { Button } from './ui/button';
	import { toggleMode, setMode, mode } from "mode-watcher";
	import Icon from '@iconify/svelte';
	import { onMount } from 'svelte';

	let m: "dark" | "light" | "system" = $mode ?? "system";

	onMount(() => {
		setMode(m);
	});
</script>

<header class="fixed top-0 flex justify-between w-full p-4">
	<LocaleSwitcher />
	<Button on:click={() => toggleMode()} variant="outline" size="icon">
		<Icon icon="bx:sun" class="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
		<Icon icon="bx:moon" class="absolute h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
		<span class="sr-only">Toggle theme</span>
	</Button>
</header>
```

**Comment by jonasfroeller** [comment]
before adding onMount(): https://svelte-kit-project-template-bj0zkacfg-jonasfroeller.vercel.app/en
after: https://svelte-kit-project-template-g0teo4sqe-jonasfroeller.vercel.app/en

**Comment by ollema** [comment]
I'm also a bit confused by this issue, there is a lot of context missing.

> Why do I have to set the mode manually onMount, if it is correctly stored in the mode store?
you do not have to set the mode manually in `onMount`. have you added the `<ModeWatcher />` component to your `+layout.svelte` as instructed in the usage section of the `README.md`
https://github.com/huntabyte/mode-watcher#usage

if this does not work, then please submit a minimal reproduction, for example by using the StackBlitz template:
https://stackblitz.com/github/huntabyte/mode-watcher

**Comment by jonasfroeller** [comment]
I somehow managed to loose my progress in the +layout.svelte file because of google drive. Thank you for your response. Just some weird cloud syncing error :/...
