### ISSUE TITLE
feature request: add `resetMode` functionality

### ISSUE THREAD

**Issue by ollema** [huntabyte/mode-watcher#6]
if you want to go back to the OS preference, then this is needed

**Comment by ollema** [comment]
actually, now that I think about it, you would not want to do:
```svelte
		<DropdownMenu.Item on:click={() => setMode(getModeOsPrefers())}>
			System
		</DropdownMenu.Item>
```
for the system option, instead you would want to reset/clear the entry in local storage right?

**Comment by huntabyte** [comment]
> actually, now that I think about it, you would not want to do:
> 
> ```svelte
> 		<DropdownMenu.Item on:click={() => setMode(getModeOsPrefers())}>
> 			System
> 		</DropdownMenu.Item>
> ```
> 
> for the system option, instead you would want to reset/clear the entry in local storage right?

That is correct! Maybe we can add a helper function to the lib like `resetMode`, which would just essentially reset it to the default (accomplishing the same thing)

**Comment by ollema** [comment]
> > actually, now that I think about it, you would not want to do:
> > ```svelte
> > 		<DropdownMenu.Item on:click={() => setMode(getModeOsPrefers())}>
> > 			System
> > 		</DropdownMenu.Item>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > for the system option, instead you would want to reset/clear the entry in local storage right?
> 
> That is correct! Maybe we can add a helper function to the lib like `resetMode`, which would just essentially reset it to the default (accomplishing the same thing)

I'll modify #7 to do that instead then!
